### PR TITLE
Fix method completion

### PR DESCRIPTION
**Pull request by BladeMF**
Changed it so it just looks at the character after the byte offset if it is a `(`. Added a test so that case `$this->my<>new SomeClass` will complete the whole signature.

### CODE REVIEW

**Comment by dantleech** [comment]
Nice that looks much safer! You need to rebase on master though I think, if not let me know and I can take over.

**Comment by BladeMF** [comment]
I probably need to update everything for that, eh?

**Comment by BladeMF** [comment]
On the failing test, can you verify that there should be no snippet? Seems strange and stared failing after rebasing.

**Comment by dantleech** [comment]
:boom:

**Pull request merged**
