### PR TITLE
remove return of class imports in use context

### PR DESCRIPTION
**Pull request by weeman1337**
relates to phpactor/language-server-phpactor-extensions#50

### CODE REVIEW

**Comment by weeman1337** [comment]
Hmm - the current `master` is failing :(

**Comment by dantleech** [comment]
yes, tolerant parser made a big BC break in prepartion for 1.0. Should be OK now.

**Comment by dantleech** [comment]
Will need a rebase on master

**Comment by weeman1337** [comment]
> yes, tolerant parser made a big BC break in prepartion for 1.0. Should be OK now (pinning to old version)

Rebased and green. Thanks

**Pull request merged**
