### PR TITLE
Fix signature helper

### PR DESCRIPTION
**Pull request by BladeMF**
Fixes https://github.com/phpactor/phpactor/issues/1168

### CODE REVIEW

**Comment by BladeMF** [comment]
BTW, is this normal - because this branch is based on the latest `master` branch it shows my merges from updating from `phpactor/completion`?

**Comment by dantleech** [comment]
Well, define "normal". you can avoid it with `git rebase origin/master` (assuming you did `git merge origin/master` or `git pull`.

you can "fix" it by `git reset --hard origin/master` `git cherry-pick c714189`. But like I say, it doesn't really matter as we squash to one commit anyway.

**Comment by BladeMF** [comment]
Well, I use the interface here to update **my** master branch from **your** master branch using a pull request. Not sure how to rebase my master from your master.

**Comment by dantleech** [comment]
You don't  really need to worry about _your_ master.

```
$ git fetch origin
```
fetches the "github" version of the code to your git repository as `origin`.

```
$ git rebase origin/master
```

will rebase your current branch on the "github" version of the code - it will apply each of your commits on the `origin/master` branch, so that your "oldest" commit has a link to the HEAD of the most recent commit on `origin/master`.

it may not work so well if you've already merged though.

**Comment by BladeMF** [comment]
This doesn't make any sense - my repo is a fork, `origin/master` should be the `master` branch of my fork in github. 

[This article](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) says how to configure another remote for my local branch. Then it says I need to [do this](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork). It says if I hadn't touched my `master` (which I wouldn't have, because I'd be using branches) it would just fast-forward mine and it will be completely in sync. Maybe I should do that.

I wonder if I can reset my master branch onto that "upstream" branch...

I am sorry about this, this is all new to me. I'll need a bit of help until I find my way.

**Comment by dantleech** [comment]
Ah yes :) I'm so used to working on the main remote, you should indeed rebase on `remote/master`

**Comment by BladeMF** [comment]
[This is how I reset, found it](https://gist.github.com/glennblock/1974465). I would guess if I don't touch my master there won't be merge commits - just a fast-fotwared.

**Comment by BladeMF** [comment]
I'd rather have my master being in sync too in case I need to use it, is my other point.

**Comment by dantleech** [comment]
yeah, i use `git fetch` `git reset --hard` in preference to `git pull` `git merge` etc.

**Comment by dantleech** [comment]
Yeah, absolutely not a problem :)

**Comment by dantleech** [comment]
Thanks, works great!

**Pull request merged**
