### PR TITLE
Fix method completion

### PR DESCRIPTION
**Pull request by dantleech**

### CODE REVIEW

**Comment by dantleech** [comment]
@BladeMF this doesn't work:

image

image

the source needs to be truncted at the offset I think.

**Comment by dantleech** [comment]
will revert this

**Comment by BladeMF** [comment]
If reverted then it can't be analysed for braces. Can you show me how that line looked while you were typing (or how it turned out afterwards, I am not sure what I am looking at)?

**Comment by dantleech** [comment]
The problem is that `$this->throw<>new Invalid` is not going to be interpreted as a member access.

**Comment by BladeMF** [comment]
how does that differ from `$this->th<>row`?

**Pull request merged**
